### ISSUE TITLE
UI / UX building

### ISSUE THREAD

**Issue by Redish03** [pknu-wap/2023_2_APP_TEAM1#2]
figma UI 만들기

우선순위별

- [x] 병 및 약 정보
- [x] 타이머
- [x] 로그인
- [x] 회원가입
- [x] 메인페이지
- [x] 과거 기록 조회

**Comment by alstjr7437** [comment]
타이머
병 및 약정보는 틀만 구성
따로 UI 꾸미기 작업 진행 예정
